title: Modelos
encoding: UTF-8
remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"
color_scheme: "dark"

baseurl: "/modelos" # Now in bash you have to do: bundle exec jekyll serve --baseurl ''

curso-actividad-practica: false
dia_aval: 12 de diciembre
