title: Modelos
encoding: UTF-8
remote_theme: just-the-docs/just-the-docs
theme: just-the-docs
color_scheme: "light"

baseurl: "/modelos" # Now in bash you have to do: bundle exec jekyll serve --baseurl ''

curso-actividad-practica: false
dia_aval: 13 de diciembre
